import google.generativeai as genai
from load_creds import load_creds
import time
import google.api_core.exceptions


async def generate_instructions(user_request: str):
    creds = load_creds()

    genai.configure(credentials=creds)

    generation_config = {
        "temperature": 1,
        "top_p": 0.95,
        "top_k": 64,
        "max_output_tokens": 8192,
        "response_mime_type": "text/plain",
    }

    safety_settings = [
        {
            "category": "HARM_CATEGORY_HARASSMENT",
            "threshold": "BLOCK_NONE"
        },
        {
            "category": "HARM_CATEGORY_HATE_SPEECH",
            "threshold": "BLOCK_NONE"
        },
        {
            "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            "threshold": "BLOCK_NONE"
        },
        {
            "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
            "threshold": "BLOCK_NONE"
        },
    ]

    model = genai.GenerativeModel(
        model_name="gemini-1.5-flash",
        generation_config=generation_config,
        safety_settings=safety_settings)

    print(user_request)

    prompt_parts = [
        "You are an interpreter that transforms natural language into commands for a Python-based code to perform actions in Discord using the discord.py library.\n\n1. Reason Requirement:\n\nWhen deleting a message, a reason is mandatory.\nIf a reason is not provided in the context, ask for one.\nEnsure a reason is not provided before asking for one.\nDo not create or assume the reason yourself if not provided.\n\n2. Handling Multiple Messages:\n\nIf multiple messages are being deleted, create an array to store them.\n\n3. Normal Conversation vs. Requests:\n\nIf the user is not making a specific request (like deleting a message) or if you don't understand their request, inform them that you didn't understand what they need.\n\n4. Parentheses vs. Brackets:\n\nSquare brackets [] indicate that the value could be an array.\nParentheses () mean the value can only be singular.\n\n5. Deleting Multiple Messages without IDs but with Parameters:\n\nUnless specific IDs are provided, a limit or both before and after parameters are needed.\n\n6. Message Deletion Criteria:\n\nIf both before and after parameters are present, disregard the limit.\nIf only one of them is present, a limit is required.\n\n7. Language Nuances:\n\nPay attention to language differences. For example, \"last message\" means delete one message, while \"last messages\" means delete multiple messages, so ask for a limit in the latter case.\n\n8. Requesting Missing Parameters:\n\nUse the input language to ask for any missing parameters when sending a message.\n\n9. Missing Channel Parameter:\n\nWhen deleting a message with no provided ID, the channel parameter is mandatory unless there's a before or after message ID.\nIf one or both of them are present, ignore the channel.\nIf there's no before or after message ID and a channel is not provided, use channel[1].\n\n10. Handling Before or After:\n\nIf before or after is a message ID, only one channel can be accepted in the channel array parameter, and that channel is ignored.\nBefore and after must be the same variable type; if before is a message ID, after must be a message ID, and vice versa for date and time.\n\n11. Date/Time Specification:\n\nUsers must be specific when providing date/time parameters.\nIf date isn't provided, use day.now, month.now, year.now.\nTime is always mandatory; concepts like \"yesterday,\" \"this month,\" \"Monday,\" \"this year,\" \"tomorrow,\" etc., are not valid.\n\n12. Comparison of Before and After Messages:\n\nWhen provided with both before and after messages, the one with the greater ID is always considered the before message.\n\n13. Limits in Message Deletion:\n\nA limit is always needed when deleting messages unless explicitly stated otherwise by the user.\nIf the user states that there's no limit, use limit(None).\nDistinguish between a user specifying no limit and not providing any limit information.\n\n14. Handling Multiple Requests:\n\nIf the user provides multiple requests in a single message, interpret each separately if the parameters are different.\nIf the parameters are the same, put them in the same command.\n\n15. Category Channels:\n\nIn Discord, a category is also considered a channel.\n\n16. Channel Permissions:\n\nThe full permissions list for a user/member or a role includes: add_reactions, administrator, attach_files, ban_members, change_nickname, connect, create_expressions, create_instant_invite, create_private_threads, create_public_threads, deafen_members, embed_links, external_emojis, external_stickers, kick_members, manage_channels, manage_emojis, manage_emojis_and_stickers, manage_events, manage_expressions, manage_guild, manage_messages, manage_nicknames, manage_permissions, manage_roles, manage_threads, manage_webhooks, mention_everyone, moderate_members, move_members, mute_members, priority_speaker, read_message_history, read_messages, request_to_speak, send_messages, send_messages_in_threads, send_tts_messages, send_voice_messages, speak, stream, use_application_commands, use_embedded_activities, use_external_emojis, use_external_sounds, use_external_stickers, use_soundboard, use_voice_activation, view_audit_log, view_channel, view_guild_insights.\n\n17. Contains vs. Attachments:\n\nUse message_contains if the user is looking for a specific word, character, emoji, etc.\nUse attachment if the user is looking for an attachment like a link, image, video, etc.\n\n18. Ban, Kick, Timeout:\n\nYou always need a reason when banning, kicking, or timing out a member\n\n19. Timeout:\nTimeout duration is optional but when provided make sure it is in the correct format and include it like I showed.\nTimeout duration valid options are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\n\n20. Ban\nWhen banning a user deleting his messages is optional but when provided make sure it is in the correct format and include it like I showed.\nMessage deletion valid options when banning one or multiple members are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days",
        "input: delete message",
        "output: sendMessage(\"Please provide the message to delete and a reason\")",
        "input: 23424234, member doesn't respect the rules",
        "output: deleteMessage[23424234] reason(\"member doesn't respect the rules\")",
        "input: Delete this message to ensure privacy. 32109876",
        "output: deleteMessage[32109876] reason(\"ensure privacy\")",
        "input: wal-i this message needs to be removed",
        "output: sendMessage(\"You didn't provide a message to delete and a reason\")",
        "input: 23424234, 32109876, member doesn't respect the rules",
        "output: deleteMessage[23424234, 32109876] reason(\"member doesn't respect the rules\")",
        "input: Can you delete this message 276876758732 ? The reason is that the member did not follow the rules.",
        "output: deleteMessage[276876758732] reason(\"member did not follow the rules\")",
        "input: Delete this message 276876758732 ? The member insulted another member.",
        "output: deleteMessage[276876758732] reason(\"member insulted another member\")",
        "input: delete the last 30 messages in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[0] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last messages in test. The member sent too many messages in a short period of time.",
        "output: sendMessage(\"Please provide a valid limit for the messages to delete\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last 30 messages in test. The member sent too many messages in a short period of time.",
        "output: deleteMessage channel[\"test\"] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the last 20 messages sent here. The member sent too many messages in a short period of time.",
        "output: deleteMessage channel[1] limit(20) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the 10 messages sent before 23423424532 in test, The member sent too pings in a short period of time.",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete the last message sent before 23423424532, The member sent too much pings in a short period of time.",
        "output: deleteMessage before(23423424532) limit(1) reason(\"The member sent too much pings in a short period of time.\")",
        "input: Delete the last messages sent before 23423424532 in test, The member sent too pings in a short period of time.",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete the last 10 messages sent before in channel test, The member sent too much pings in a short period of time.",
        "output: sendMessage(\"You didn't provide a valid before parameter\")",
        "input: 23423424532",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages sent after 2375672242 in channel test, The member sent too much pings in a short period of time.",
        "output: deleteMessage after(2375672242) limit(10) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages sent after 2375672242.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage after(2375672242) limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the messages sent after 2375672242 and before 23423424532 in channel test.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: member isn't respecting the rules",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"member isn't respecting the rules\")",
        "input: delete the messages sent after 2375672242 and before 23423424532 in channel test. The member sent too much pings in a short period of time.",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the messages sent after and before 23423424532 in channel test. The member sent too much pings in a short period of time.",
        "output: sendMessage(\"Please provide a valid after parameter\")",
        "input: 2375672242",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages ali sent in channel test",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last 10 messages the member ali sent in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(10) reason(\"He sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages I sent in channel test.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[\"test\"] member[1] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the 20 messages ali sent before 23423424532 in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage member[\"ali\"] before(23423424532) limit(20) reason(\"He sent too much pings in a short period of time.\")",
        "input: Delete the 20 messages ali sent after 34534563464 in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage member[\"ali\"] after(34534563464) limit(20) reason(\"He sent too much pings in a short period of time.\")",
        "input: delete messages with stp and 🫡 in channel test sent by ali, member is insulting",
        "output: sendMessage(\"What is the limit please\")",
        "input: no limit",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] message_contains[\"stp\", \"🫡\"] limit(None) reason(\"member is insulting\")",
        "input: delete messages with stp in channel test sent by ali before this message 23453534536, member is making an insult.",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] before(23453534536) limit(10) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532, member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536, member is making an insult.",
        "output: sendMessage(\"Please provide me with a limit\")",
        "input: limit none",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) limit(None) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532 limit 10, member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532. member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete all messages containing stupid, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] message_contains[\"stupid\"] limit(10) reason(\"I am testing something\")",
        "input: delete all messages with links, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[1] attachement[\"links\"] limit(None) reason(\"I am testing something\")",
        "input: delete any message with image in channel test, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] attachement[\"image\"] limit(10) reason(\"I am testing something\")",
        "input: delete all messages with video in channel test, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[\"test\"] attachement[\"video\"] limit(None) reason(\"I am testing something\")",
        "input: delete all messages sent by ali",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage member[\"ali\"] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last message sent here",
        "output: sendMessage(\"Please provide a reason for deleting that message\")",
        "input: member is making an insult.",
        "output: deleteMessage channel[1] limit(1) reason(\"member is making an insult.\")",
        "input: delete messages in all channel",
        "output: sendMessage(\"Please provide a reason for deleting those messages plus a limit\")",
        "input: Doing a server cleanup, limit 100",
        "output: deleteMessage channel[0] limit(100) reason(\"Doing a server cleanup\")",
        "input: delete the last messages in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those message and a limit\")",
        "input: The members were insulting each other when I was gone, limit 134",
        "output: deleteMessage channel[0] limit(134) reason(\"The members were insulting each other when I was gone\")",
        "input: delete messages with any attachement, member are not authorized to send attachements",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] attachement[\"all\"] limit(10) reason(\"member are not authorized to send attachements\")",
        "input: delete the last 10 messages in all channels with any attachement, member are not authorized to send attachements",
        "output: deleteMessage channel[0] attachement[\"all\"] limit(10) reason(\"member are not authorized to send attachements\")",
        "input: delete the last 10 messages I sent, I am testing something",
        "output: deleteMessage channel[1] member[1] limit(10) reason(\"I am testing something\")",
        "input: could you delete the messages sent by <@905696511197872169>",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: limit none, he is being disrespectful",
        "output: deleteMessage channel[1] member[905696511197872169] limit(None) reason(\"he is being disrespectful\")",
        "input: <@905696511197872169> sent multiple messages at the same time could you delete them",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] member[905696511197872169] limit(10) reason(\"he sent multiple messages at the same time\")",
        "input: Delete messages sent before the 12 october 2023 in all channels, The members sent too much pings in a short period of time.",
        "output: sendMessage(\"Please provide me with a limit.\")",
        "input: 200",
        "output: deleteMessage channel[0] before(2023-10-12 00:00:00) limit(200) reason(\"The members sent too pings in a short period of time.\")",
        "input: Delete all messages sent after the 23 january at 12am in all channels, doing a server cleanup.",
        "output: deleteMessage channel[0] after(2023-01-23 12:00:00) limit(None) reason(\"Doing a server cleanup.\")",
        "input: Delete the 10 messages sent after the 23 january at 12am and before 12pm in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(2023-01-23 12:00:00) before(2023-02-23 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent today at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(year.now-month.now-day.now 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent yesterday at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"Please provide me with a valid time: appart from today which I understand that it's the current day other terms like tomorrow, this month, this year, this week, monday, tuesday, yesterday etc... aren't valid\\\")",
        "input: Delete the 10 messages sent the 12 september at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(2023-09-12 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent after 235254364 and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"You can't use a date and time with a message id on before/after\")",
        "input: Delete the 10 messages sent after 235254364 and before 235254364 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"To delete messages in multiple channels using before/after you need a date and time.\")",
        "input: the 12 september at 12am and before the 12 october 2023",
        "output: deleteMessage channel[0] after(2023-09-12 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete message sent before the 12 may of this year and after the 4 january",
        "output: sendMessage(\"Please provide me with valid dates; you can't use this year, this month, etc..., also provide a reason\")",
        "input: 2024, I am doing a server a cleanup",
        "output: deleteMessage channel[1] after(2024-01-04 00:00:00) before(2024-05-12 00:00:00) reason(\"I am doing a server a cleanup\")",
        "input: delete messages between 1241628887868506164 and 1241628917136359514",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: Just checking if one of your functionalities is working",
        "output: deleteMessage after(1241628887868506164) before(1241628917136359514) reason(\"Just checking if one of your functionalities is working.\")",
        "input: delete message between 1241628906767913031 and 1240968371143704607, I am trying to see something",
        "output: deleteMessage after(1240968371143704607) before(1241628906767913031) reason(\"I am trying to see something\")",
        "input: delete all messages sent in channel test and wal-i, just trying something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: None",
        "output: deleteMessage channel[\"test\", \"wal-i\"] limit(None) reason(\"just trying something\")",
        "input: delete all messages I sent in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: I am testing something, no limit",
        "output: deleteMessage channel[0] member[1] limit(None) reason(\"I am testing something\")",
        "input: delete all messages sent by me",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: I am testing something, no limit",
        "output: deleteMessage channel[1] member[1] limit(None) reason(\"I am testing something\")",
        "input: make the following channel private",
        "output: sendMessage(\"Please provide me with the channels\")",
        "input: RN",
        "output: updateChannel[\"RN\"] role[\"everyone\"] removePermissons[\"read_messages\"]",
        "input: let everyone access the following channel DF",
        "output: updateChannel[\"DF\"] role[\"everyone\"] addPermissons[\"read_messages\"]",
        "input: Let the role gost access the following channel DF",
        "output: updateChannel[\"DF\"] role[\"gost\"] addPermissons[\"read_messages\"]",
        "input: give member permission to add attachements in the following channel DF",
        "output: updateChannel[\"DF\"] role[\"everyone\"] addPermissons[\"attach_files\"]",
        "input: remove sali permission to send message in the following channel DF and gost",
        "output: updateChannel[\"DF\", \"gost\"] role[\"sali\"] removePermissons[\"send_messages\", \"send_messages_in_threads\"]",
        "input: reverse WAssap channel to private",
        "output: updateChannel[\"WAssap\"] role[\"everyone\"] removePermissons[\"read_messages\"]",
        "input: add the role admin to the following channel DF",
        "output: updateChannel[\"DF\"] role[\"admin\"] addPermissons[\"read_messages\"]",
        "input: remove the role ldfg to ali",
        "output: editMember[\"ali\"] removeRole[\"ldfg\"]",
        "input: add the role ldfg to ali",
        "output: editMember[\"ali\"] addRole[\"ldfg\"]",
        "input: mute ali",
        "output: editMember[\"ali\"] mute",
        "input: unmute ali",
        "output: editMember[\"ali\"] unmute",
        "input: ban ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] ban reason(\"He insulted another member.\")",
        "input: kick ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] kick reason(\"He insulted another member.\")",
        "input: Timeout ali",
        "output: sendMessage(\"Please provide a reason and duration options are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: He insulted another member. 1 HOUR",
        "output: editMember[\"ali\"] timeout duration(\"1 HOUR\") reason(\"He insulted another member.\")",
        "input: mute ali soundboard",
        "output: editMember[\"ali\"] muteSoundBoard",
        "input: unmute ali soundboard",
        "output: editMember[\"ali\"] unmuteSoundBoard",
        "input: ban ali and delete the last messages he sent, he doesn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 24 Hours",
        "output: editMember[\"ali\"] ban reason(\"he doesn't follow the rules\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali, he doesn't follow the rules",
        "output: editMember[\"ali\"] ban reason(\"he doesn't follow the rules\")",
        "input: kick ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] kick reason(\"He insulted another member\")",
        "input: kick legarsolo",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"legarsolo\"] kick reason(\"He insulted another member.\")",
        "input: delete all message ali sent in channel test, and messages sam sent in channel farl",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit for ali and 30 for sam",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(None) reason(\"The member sent too many messages in a short period of time.\"), deleteMessage channel[\"farl\"] member[\"sam\"] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete all messages ali and sam sent in channel test, they are being disrespectful",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] member[\"ali\", \"sam\"] limit(10) reason(\"they are being disrespectful\")",
        "input: delete the last 20 messages ali sent in channel farl, and the last 10 messages sam sent in channel test. They are being disrespectful",
        "output: deleteMessage channel[\"farl\"] member[\"ali\"] limit(20) reason(\"They are being disrespectful\"), deleteMessage channel[\"test\"] member[\"sam\"] limit(10) reason(\"They are being disrespectful\")",
        "input: I would like for you to delete all messages sent here",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage channel[1] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete all messages sent here",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage channel[1] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Hi wali, how are you ?",
        "output: sendMessage(\"Hi there! I'm doing well, thank you. How can I help you today?\")",
        "input: kick <@644988173428064266>",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is not following the rules",
        "output: editMember[644988173428064266] kick reason(\"He is not following the rules\")",
        "input: delete message sent by 1234567890, member is spamming",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] member[1234567890] limit(10) reason(\"member is spamming\")",
        "input: delete messages in all channels before 12 March 2024, cleaning up",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 100",
        "output: deleteMessage channel[0] before(2024-03-12 00:00:00) limit(100) reason(\"cleaning up\")",
        "input: delete last 50 messages in channel general, member is flooding",
        "output: deleteMessage channel[\"general\"] limit(50) reason(\"member is flooding\")",
        "input: delete message 9876543210, violation of rules",
        "output: deleteMessage[9876543210] reason(\"violation of rules\")",
        "input: remove role moderator from member 1122334455",
        "output: editMember[1122334455] removeRole[\"moderator\"]",
        "input: add role admin to member 1122334455",
        "output: editMember[1122334455] addRole[\"admin\"]",
        "input: ban member 9988776655, spamming in multiple channels",
        "output: editMember[9988776655] ban reason(\"spamming in multiple channels\")",
        "input: delete all messages from member 9988776655 in channel general, no limit",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: member is continuously spamming",
        "output: deleteMessage channel[\"general\"] member[9988776655] limit(None) reason(\"member is continuously spamming\")",
        "input: kick member 4433221100, inappropriate behavior",
        "output: editMember[4433221100] kick reason(\"inappropriate behavior\")",
        "input: timeout member 3344556677 for 5 mins, offensive language",
        "output: editMember[3344556677] timeout duration(\"5 MINS\") reason(\"member used offensive language\")",
        "input: delete messages from member 2233445566 containing 'spoiler', max 20, inappropriate content",
        "output: deleteMessage channel[1] member[2233445566] message_contains[\"spoiler\"] limit(20) reason(\"inappropriate content\")",
        "input: delete messages from member 5566778899 before message 9988776655, limit 15, cleanup",
        "output: deleteMessage member[5566778899] before(9988776655) limit(15) reason(\"cleanup\")",
        "input: mute soundboard member 4455667788, being disruptive",
        "output: editMember[4455667788] muteSoundBoard",
        "input: delete all messages containing 'spam' in all channels, limit 50",
        "output: sendMessage(\"Please provide a reason\")",
        "input: removing spam content",
        "output: deleteMessage channel[0] message_contains[\"spam\"] limit(50) reason(\"removing spam content\")",
        "input: delete all messages with images in general channel, limit 30, image spam",
        "output: deleteMessage channel[\"general\"] attachement[\"image\"] limit(30) reason(\"image spam\")",
        "input: delete messages from 20 June 2023 in all channels, no limit, cleanup",
        "output: sendMessage(\"Please provide a reason\")",
        "input: cleanup required",
        "output: deleteMessage channel[0] after(2023-06-20 00:00:00) limit(None) reason(\"cleanup required\")",
        "input: delete messages with videos in channel media, limit 10, media cleanup",
        "output: deleteMessage channel[\"media\"] attachement[\"video\"] limit(10) reason(\"media cleanup\")",
        "input: unmute soundboard member 1122334455",
        "output: editMember[1122334455] unmuteSoundBoard",
        "input: add role moderator to member 5566778899",
        "output: editMember[5566778899] addRole[\"moderator\"]",
        "input: remove role guest from member 9988776655",
        "output: editMember[9988776655] removeRole[\"guest\"]",
        "input: delete all messages from 1231231231 and 3213213213 in all channels, they are spamming",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[0] member[1231231231, 3213213213] limit(None) reason(\"they are spamming\")",
        "input: delete last 15 messages from member 2342342342 in channel rules, they are breaking rules",
        "output: deleteMessage channel[\"rules\"] member[2342342342] limit(15) reason(\"they are breaking rules\")",
        "input: ban ali and delete all messages he sent, he is insulting others",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 24 Hours",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali, he is insulting others",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\")",
        "input: kick ali, duration 1 day, he is being disrespectful",
        "output: editMember[\"ali\"] kick duration(\"1 DAY\") reason(\"he is being disrespectful\")",
        "input: ban ami and delete all the message she sent, she didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 3 Days",
        "output: editMember[\"ami\"] ban reason(\"she didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: Timeout ali for 24h hours he deidn't respect the rules",
        "output: editMember[\"ali\"] timeout duration(\"1 DAY\") reason(\"he didn't respect the rules\")",
        "input: ban alex and delete all the message he sent, he didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: 24h",
        "output: editMember[\"alex\"] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban pierre and delete the messages he sent in the last 6h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"pierre\"] ban reason(\"He is being disrespectful\") deleteMessage(\"Previous 6 Hours\")",
        "input: kick chabrier for 3h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"chabrier\"] kick reason(\"He is being disrespectful\")",
        "input: timeout <@644988173428064266> for 3h , being disrespectful",
        "output: sendMessage(\"valid timeout duration are 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 3h",
        "output: sendMessage(\"valid timeout duration are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 1h",
        "output: editMember[644988173428064266] timeout duration(\"1 HOUR\") reason(\"being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days",
        "output: sendMessage(\"Please provide a reason, and valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: He is being disrespectful",
        "output: editMember[644988173428064266] ban reason(\"He is being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days, he didn't follow the rules",
        "output: sendMessage(\"Valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: Previous 3 days",
        "output: editMember[644988173428064266] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: He disrespected the rules enough, 7 days",
        "output: editMember[1154566609856385067] ban reason(\"He disrespected the rules enough\") deleteMessage(\"Previous 7 Days\")",
        "input: ban <@1154566609856385067> and delete all the messages he sent",
        "output: sendMessage(\"Please provide a reason for the ban, and valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: delete message",
        "output: sendMessage(\"Please provide the message to delete and a reason\")",
        "input: 23424234, member doesn't respect the rules",
        "output: deleteMessage[23424234] reason(\"member doesn't respect the rules\")",
        "input: Delete this message to ensure privacy. 32109876",
        "output: deleteMessage[32109876] reason(\"ensure privacy\")",
        "input: wal-i this message needs to be removed",
        "output: sendMessage(\"You didn't provide a message to delete and a reason\")",
        "input: 23424234, 32109876, member doesn't respect the rules",
        "output: deleteMessage[23424234, 32109876] reason(\"member doesn't respect the rules\")",
        "input: Can you delete this message 276876758732 ? The reason is that the member did not follow the rules.",
        "output: deleteMessage[276876758732] reason(\"member did not follow the rules\")",
        "input: Delete this message 276876758732 ? The member insulted another member.",
        "output: deleteMessage[276876758732] reason(\"member insulted another member\")",
        "input: delete the last 30 messages in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[0] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last messages in test. The member sent too many messages in a short period of time.",
        "output: sendMessage(\"Please provide a valid limit for the messages to delete\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last 30 messages in test. The member sent too many messages in a short period of time.",
        "output: deleteMessage channel[\"test\"] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the last 20 messages sent here. The member sent too many messages in a short period of time.",
        "output: deleteMessage channel[1] limit(20) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the 10 messages sent before 23423424532 in test, The member sent too pings in a short period of time.",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete the last message sent before 23423424532, The member sent too much pings in a short period of time.",
        "output: deleteMessage before(23423424532) limit(1) reason(\"The member sent too much pings in a short period of time.\")",
        "input: Delete the last messages sent before 23423424532 in test, The member sent too pings in a short period of time.",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete the last 10 messages sent before in channel test, The member sent too much pings in a short period of time.",
        "output: sendMessage(\"You didn't provide a valid before parameter\")",
        "input: 23423424532",
        "output: deleteMessage before(23423424532) limit(10) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages sent after 2375672242 in channel test, The member sent too much pings in a short period of time.",
        "output: deleteMessage after(2375672242) limit(10) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages sent after 2375672242.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage after(2375672242) limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the messages sent after 2375672242 and before 23423424532 in channel test.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: member isn't respecting the rules",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"member isn't respecting the rules\")",
        "input: delete the messages sent after 2375672242 and before 23423424532 in channel test. The member sent too much pings in a short period of time.",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the messages sent after and before 23423424532 in channel test. The member sent too much pings in a short period of time.",
        "output: sendMessage(\"Please provide a valid after parameter\")",
        "input: 2375672242",
        "output: deleteMessage after(2375672242) before(23423424532) reason(\"The member sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages ali sent in channel test",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last 10 messages the member ali sent in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(10) reason(\"He sent too much pings in a short period of time.\")",
        "input: delete the last 10 messages I sent in channel test.",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: The member sent too many messages in a short period of time",
        "output: deleteMessage channel[\"test\"] member[1] limit(10) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Delete the 20 messages ali sent before 23423424532 in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage member[\"ali\"] before(23423424532) limit(20) reason(\"He sent too much pings in a short period of time.\")",
        "input: Delete the 20 messages ali sent after 34534563464 in channel test. He sent too much pings in a short period of time.",
        "output: deleteMessage member[\"ali\"] after(34534563464) limit(20) reason(\"He sent too much pings in a short period of time.\")",
        "input: delete messages with stp and 🫡 in channel test sent by ali, member is insulting",
        "output: sendMessage(\"What is the limit please\")",
        "input: no limit",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] message_contains[\"stp\", \"🫡\"] limit(None) reason(\"member is insulting\")",
        "input: delete messages with stp in channel test sent by ali before this message 23453534536, member is making an insult.",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] before(23453534536) limit(10) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532, member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536, member is making an insult.",
        "output: sendMessage(\"Please provide me with a limit\")",
        "input: limit none",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) limit(None) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532 limit 10, member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete messages with stp in channel test sent by ali after 23453534536 and before 23423424532. member is making an insult.",
        "output: deleteMessage member[\"ali\"] message_contains[\"stp\"] after(23453534536) before(23423424532) reason(\"member is making an insult.\")",
        "input: delete all messages containing stupid, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] message_contains[\"stupid\"] limit(10) reason(\"I am testing something\")",
        "input: delete all messages with links, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[1] attachement[\"links\"] limit(None) reason(\"I am testing something\")",
        "input: delete any message with image in channel test, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] attachement[\"image\"] limit(10) reason(\"I am testing something\")",
        "input: delete all messages with video in channel test, I am testing something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[\"test\"] attachement[\"video\"] limit(None) reason(\"I am testing something\")",
        "input: delete all messages sent by ali",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage member[\"ali\"] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete the last message sent here",
        "output: sendMessage(\"Please provide a reason for deleting that message\")",
        "input: member is making an insult.",
        "output: deleteMessage channel[1] limit(1) reason(\"member is making an insult.\")",
        "input: delete messages in all channel",
        "output: sendMessage(\"Please provide a reason for deleting those messages plus a limit\")",
        "input: Doing a server cleanup, limit 100",
        "output: deleteMessage channel[0] limit(100) reason(\"Doing a server cleanup\")",
        "input: delete the last messages in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those message and a limit\")",
        "input: The members were insulting each other when I was gone, limit 134",
        "output: deleteMessage channel[0] limit(134) reason(\"The members were insulting each other when I was gone\")",
        "input: delete messages with any attachement, member are not authorized to send attachements",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] attachement[\"all\"] limit(10) reason(\"member are not authorized to send attachements\")",
        "input: delete the last 10 messages in all channels with any attachement, member are not authorized to send attachements",
        "output: deleteMessage channel[0] attachement[\"all\"] limit(10) reason(\"member are not authorized to send attachements\")",
        "input: delete the last 10 messages I sent, I am testing something",
        "output: deleteMessage channel[1] member[1] limit(10) reason(\"I am testing something\")",
        "input: could you delete the messages sent by <@905696511197872169>",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: limit none, he is being disrespectful",
        "output: deleteMessage channel[1] member[905696511197872169] limit(None) reason(\"he is being disrespectful\")",
        "input: <@905696511197872169> sent multiple messages at the same time could you delete them",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] member[905696511197872169] limit(10) reason(\"he sent multiple messages at the same time\")",
        "input: Delete messages sent before the 12 october 2023 in all channels, The members sent too much pings in a short period of time.",
        "output: sendMessage(\"Please provide me with a limit.\")",
        "input: 200",
        "output: deleteMessage channel[0] before(2023-10-12 00:00:00) limit(200) reason(\"The members sent too pings in a short period of time.\")",
        "input: Delete all messages sent after the 23 january at 12am in all channels, doing a server cleanup.",
        "output: deleteMessage channel[0] after(2023-01-23 12:00:00) limit(None) reason(\"Doing a server cleanup.\")",
        "input: Delete the 10 messages sent after the 23 january at 12am and before 12pm in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(2023-01-23 12:00:00) before(2023-02-23 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent today at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(year.now-month.now-day.now 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent yesterday at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"Please provide me with a valid time: appart from today which I understand that it's the current day other terms like tomorrow, this month, this year, this week, monday, tuesday, yesterday etc... aren't valid\\\")",
        "input: Delete the 10 messages sent the 12 september at 12am and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: deleteMessage channel[0] after(2023-09-12 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: Delete the 10 messages sent after 235254364 and before the 12 october 2023 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"You can't use a date and time with a message id on before/after\")",
        "input: Delete the 10 messages sent after 235254364 and before 235254364 in all channels, The member sent too pings in a short period of time",
        "output: sendMessage(\"To delete messages in multiple channels using before/after you need a date and time.\")",
        "input: the 12 september at 12am and before the 12 october 2023",
        "output: deleteMessage channel[0] after(2023-09-12 12:00:00) before(2023-10-12 00:00:00) reason(\"The member sent too pings in a short period of time.\")",
        "input: delete message sent before the 12 may of this year and after the 4 january",
        "output: sendMessage(\"Please provide me with valid dates; you can't use this year, this month, etc..., also provide a reason\")",
        "input: 2024, I am doing a server a cleanup",
        "output: deleteMessage channel[1] after(2024-01-04 00:00:00) before(2024-05-12 00:00:00) reason(\"I am doing a server a cleanup\")",
        "input: delete messages between 1241628887868506164 and 1241628917136359514",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: Just checking if one of your functionalities is working",
        "output: deleteMessage after(1241628887868506164) before(1241628917136359514) reason(\"Just checking if one of your functionalities is working.\")",
        "input: delete message between 1241628906767913031 and 1240968371143704607, I am trying to see something",
        "output: deleteMessage after(1240968371143704607) before(1241628906767913031) reason(\"I am trying to see something\")",
        "input: delete all messages sent in channel test and wal-i, just trying something",
        "output: sendMessage(\"Please provide a limit\")",
        "input: None",
        "output: deleteMessage channel[\"test\", \"wal-i\"] limit(None) reason(\"just trying something\")",
        "input: delete all messages I sent in all channels",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: I am testing something, no limit",
        "output: deleteMessage channel[0] member[1] limit(None) reason(\"I am testing something\")",
        "input: delete all messages sent by me",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: I am testing something, no limit",
        "output: deleteMessage channel[1] member[1] limit(None) reason(\"I am testing something\")",
        "input: make the following channel private",
        "output: sendMessage(\"Please provide me with the channels\")",
        "input: RN",
        "output: updateChannel[\"RN\"] role[\"everyone\"] removePermissons[\"read_messages\"]",
        "input: let everyone access the following channel DF",
        "output: updateChannel[\"DF\"] role[\"everyone\"] addPermissons[\"read_messages\"]",
        "input: Let the role gost access the following channel DF",
        "output: updateChannel[\"DF\"] role[\"gost\"] addPermissons[\"read_messages\"]",
        "input: give member permission to add attachements in the following channel DF",
        "output: updateChannel[\"DF\"] role[\"everyone\"] addPermissons[\"attach_files\"]",
        "input: remove sali permission to send message in the following channel DF and gost",
        "output: updateChannel[\"DF\", \"gost\"] role[\"sali\"] removePermissons[\"send_messages\", \"send_messages_in_threads\"]",
        "input: reverse WAssap channel to private",
        "output: updateChannel[\"WAssap\"] role[\"everyone\"] removePermissons[\"read_messages\"]",
        "input: add the role admin to the following channel DF",
        "output: updateChannel[\"DF\"] role[\"admin\"] addPermissons[\"read_messages\"]",
        "input: remove the role ldfg to ali",
        "output: editMember[\"ali\"] removeRole[\"ldfg\"]",
        "input: add the role ldfg to ali",
        "output: editMember[\"ali\"] addRole[\"ldfg\"]",
        "input: mute ali",
        "output: editMember[\"ali\"] mute",
        "input: unmute ali",
        "output: editMember[\"ali\"] unmute",
        "input: ban ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] ban reason(\"He insulted another member.\")",
        "input: kick ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] kick reason(\"He insulted another member.\")",
        "input: Timeout ali",
        "output: sendMessage(\"Please provide a reason and duration options are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: He insulted another member. 1 HOUR",
        "output: editMember[\"ali\"] timeout duration(\"1 HOUR\") reason(\"He insulted another member.\")",
        "input: mute ali soundboard",
        "output: editMember[\"ali\"] muteSoundBoard",
        "input: unmute ali soundboard",
        "output: editMember[\"ali\"] unmuteSoundBoard",
        "input: ban ali and delete the last messages he sent, he doesn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 24 Hours",
        "output: editMember[\"ali\"] ban reason(\"he doesn't follow the rules\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali, he doesn't follow the rules",
        "output: editMember[\"ali\"] ban reason(\"he doesn't follow the rules\")",
        "input: kick ali",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"ali\"] kick reason(\"He insulted another member\")",
        "input: kick legarsolo",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He insulted another member.",
        "output: editMember[\"legarsolo\"] kick reason(\"He insulted another member.\")",
        "input: delete all message ali sent in channel test, and messages sam sent in channel farl",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit for ali and 30 for sam",
        "output: deleteMessage channel[\"test\"] member[\"ali\"] limit(None) reason(\"The member sent too many messages in a short period of time.\"), deleteMessage channel[\"farl\"] member[\"sam\"] limit(30) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete all messages ali and sam sent in channel test, they are being disrespectful",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[\"test\"] member[\"ali\", \"sam\"] limit(10) reason(\"they are being disrespectful\")",
        "input: delete the last 20 messages ali sent in channel farl, and the last 10 messages sam sent in channel test. They are being disrespectful",
        "output: deleteMessage channel[\"farl\"] member[\"ali\"] limit(20) reason(\"They are being disrespectful\"), deleteMessage channel[\"test\"] member[\"sam\"] limit(10) reason(\"They are being disrespectful\")",
        "input: I would like for you to delete all messages sent here",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage channel[1] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: delete all messages sent here",
        "output: sendMessage(\"Please provide a reason for deleting those messages, and a limit\")",
        "input: The member sent too many messages in a short period of time, no limit",
        "output: deleteMessage channel[1] limit(None) reason(\"The member sent too many messages in a short period of time.\")",
        "input: Hi wali, how are you ?",
        "output: sendMessage(\"Hi there! I'm doing well, thank you. How can I help you today?\")",
        "input: kick <@644988173428064266>",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is not following the rules",
        "output: editMember[644988173428064266] kick reason(\"He is not following the rules\")",
        "input: delete message sent by 1234567890, member is spamming",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 10",
        "output: deleteMessage channel[1] member[1234567890] limit(10) reason(\"member is spamming\")",
        "input: delete messages in all channels before 12 March 2024, cleaning up",
        "output: sendMessage(\"Please provide a limit\")",
        "input: 100",
        "output: deleteMessage channel[0] before(2024-03-12 00:00:00) limit(100) reason(\"cleaning up\")",
        "input: delete last 50 messages in channel general, member is flooding",
        "output: deleteMessage channel[\"general\"] limit(50) reason(\"member is flooding\")",
        "input: delete message 9876543210, violation of rules",
        "output: deleteMessage[9876543210] reason(\"violation of rules\")",
        "input: remove role moderator from member 1122334455",
        "output: editMember[1122334455] removeRole[\"moderator\"]",
        "input: add role admin to member 1122334455",
        "output: editMember[1122334455] addRole[\"admin\"]",
        "input: ban member 9988776655, spamming in multiple channels",
        "output: editMember[9988776655] ban reason(\"spamming in multiple channels\")",
        "input: delete all messages from member 9988776655 in channel general, no limit",
        "output: sendMessage(\"Please provide a reason for deleting those messages\")",
        "input: member is continuously spamming",
        "output: deleteMessage channel[\"general\"] member[9988776655] limit(None) reason(\"member is continuously spamming\")",
        "input: kick member 4433221100, inappropriate behavior",
        "output: editMember[4433221100] kick reason(\"inappropriate behavior\")",
        "input: timeout member 3344556677 for 5 mins, offensive language",
        "output: editMember[3344556677] timeout duration(\"5 MINS\") reason(\"member used offensive language\")",
        "input: delete messages from member 2233445566 containing 'spoiler', max 20, inappropriate content",
        "output: deleteMessage channel[1] member[2233445566] message_contains[\"spoiler\"] limit(20) reason(\"inappropriate content\")",
        "input: delete messages from member 5566778899 before message 9988776655, limit 15, cleanup",
        "output: deleteMessage member[5566778899] before(9988776655) limit(15) reason(\"cleanup\")",
        "input: mute soundboard member 4455667788, being disruptive",
        "output: editMember[4455667788] muteSoundBoard",
        "input: delete all messages containing 'spam' in all channels, limit 50",
        "output: sendMessage(\"Please provide a reason\")",
        "input: removing spam content",
        "output: deleteMessage channel[0] message_contains[\"spam\"] limit(50) reason(\"removing spam content\")",
        "input: delete all messages with images in general channel, limit 30, image spam",
        "output: deleteMessage channel[\"general\"] attachement[\"image\"] limit(30) reason(\"image spam\")",
        "input: delete messages from 20 June 2023 in all channels, no limit, cleanup",
        "output: sendMessage(\"Please provide a reason\")",
        "input: cleanup required",
        "output: deleteMessage channel[0] after(2023-06-20 00:00:00) limit(None) reason(\"cleanup required\")",
        "input: delete messages with videos in channel media, limit 10, media cleanup",
        "output: deleteMessage channel[\"media\"] attachement[\"video\"] limit(10) reason(\"media cleanup\")",
        "input: unmute soundboard member 1122334455",
        "output: editMember[1122334455] unmuteSoundBoard",
        "input: add role moderator to member 5566778899",
        "output: editMember[5566778899] addRole[\"moderator\"]",
        "input: remove role guest from member 9988776655",
        "output: editMember[9988776655] removeRole[\"guest\"]",
        "input: delete all messages from 1231231231 and 3213213213 in all channels, they are spamming",
        "output: sendMessage(\"Please provide a limit\")",
        "input: no limit",
        "output: deleteMessage channel[0] member[1231231231, 3213213213] limit(None) reason(\"they are spamming\")",
        "input: delete last 15 messages from member 2342342342 in channel rules, they are breaking rules",
        "output: deleteMessage channel[\"rules\"] member[2342342342] limit(15) reason(\"they are breaking rules\")",
        "input: ban ali and delete all messages he sent, he is insulting others",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 24 Hours",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali, he is insulting others",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\")",
        "input: kick ali, duration 1 day, he is being disrespectful",
        "output: editMember[\"ali\"] kick duration(\"1 DAY\") reason(\"he is being disrespectful\")",
        "input: ban ami and delete all the message she sent, she didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 3 Days",
        "output: editMember[\"ami\"] ban reason(\"she didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: Timeout ali for 24h hours he deidn't respect the rules",
        "output: editMember[\"ali\"] timeout duration(\"1 DAY\") reason(\"he didn't respect the rules\")",
        "input: ban alex and delete all the message he sent, he didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: 24h",
        "output: editMember[\"alex\"] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban pierre and delete the messages he sent in the last 6h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"pierre\"] ban reason(\"He is being disrespectful\") deleteMessage(\"Previous 6 Hours\")",
        "input: kick chabrier for 3h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"chabrier\"] kick reason(\"He is being disrespectful\")",
        "input: timeout <@644988173428064266> for 3h , being disrespectful",
        "output: sendMessage(\"valid timeout duration are 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 3h",
        "output: sendMessage(\"valid timeout duration are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 1h",
        "output: editMember[644988173428064266] timeout duration(\"1 HOUR\") reason(\"being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days",
        "output: sendMessage(\"Please provide a reason, and valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: He is being disrespectful",
        "output: editMember[644988173428064266] ban reason(\"He is being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days, he didn't follow the rules",
        "output: sendMessage(\"Valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: Previous 3 days",
        "output: editMember[644988173428064266] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: delete all the message ali sent and ban him",
        "output: sendMessage(\"Please provide a limit and reason for deleting the messages, and the reason for banning him\")",
        "input: limit none, he is being disrespectful",
        "output: deleteMessage channel[1] member[\"ali\"] limit(None) reason(\"he is being disrespectful\"), editMember[\"ali\"] ban reason(\"he is being disrespectful\")",
        "input: ban ali and delete all the messages he sent",
        "output: sendMessage(\"What is the reason, and be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: He broke the rules 3 times, previous 24h",
        "output: editMember[\"ali\"] ban reason(\"He broke the rules 3 times\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali and delete all messages he sent, he is insulting others",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 24 Hours",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali, he is insulting others",
        "output: editMember[\"ali\"] ban reason(\"he is insulting others\")",
        "input: kick ali, duration 1 day, he is being disrespectful",
        "output: editMember[\"ali\"] kick duration(\"1 DAY\") reason(\"he is being disrespectful\")",
        "input: ban ami and delete all the message she sent, she didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: Previous 3 Days",
        "output: editMember[\"ami\"] ban reason(\"she didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: Timeout ali for 24h hours he deidn't respect the rules",
        "output: editMember[\"ali\"] timeout duration(\"1 DAY\") reason(\"he didn't respect the rules\")",
        "input: ban alex and delete all the message he sent, he didn't follow the rules",
        "output: sendMessage(\"Please be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: 24h",
        "output: editMember[\"alex\"] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban pierre and delete the messages he sent in the last 6h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"pierre\"] ban reason(\"He is being disrespectful\") deleteMessage(\"Previous 6 Hours\")",
        "input: kick chabrier for 3h",
        "output: sendMessage(\"Please provide a reason\")",
        "input: He is being disrespectful",
        "output: editMember[\"chabrier\"] kick reason(\"He is being disrespectful\")",
        "input: timeout <@644988173428064266> for 3h , being disrespectful",
        "output: sendMessage(\"valid timeout duration are 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 3h",
        "output: sendMessage(\"valid timeout duration are: 60 SECS, 5 MINS, 10 MINS, 1 HOUR, 1 DAY, and 1 WEEK\")",
        "input: 1h",
        "output: editMember[644988173428064266] timeout duration(\"1 HOUR\") reason(\"being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days",
        "output: sendMessage(\"Please provide a reason, and valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: He is being disrespectful",
        "output: editMember[644988173428064266] ban reason(\"He is being disrespectful\")",
        "input: ban <@644988173428064266> , and all the message he sent in the last days, he didn't follow the rules",
        "output: sendMessage(\"Valid options for message deletion when banning a user are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days, Previous 7 Days\")",
        "input: Previous 3 days",
        "output: editMember[644988173428064266] ban reason(\"he didn't follow the rules\") deleteMessage(\"Previous 3 Days\")",
        "input: delete all the message ali sent and ban him",
        "output: sendMessage(\"Please provide a limit and reason for deleting the messages, and the reason for banning him\")",
        "input: limit none, he is being disrespectful",
        "output: deleteMessage channel[1] member[\"ali\"] limit(None) reason(\"he is being disrespectful\"), editMember[\"ali\"] ban reason(\"he is being disrespectful\")",
        "input: ban ali and delete all the messages he sent",
        "output: sendMessage(\"What is the reason for banning him, and be precise for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        "input: He broke the rules 3 times, previous 24h",
        "output: editMember[\"ali\"] ban reason(\"He broke the rules 3 times\") deleteMessage(\"Previous 24 Hours\")",
        "input: ban ali and delete all the messages he sent",
        "output: sendMessage(\"What is the reason for banning him, for the message deletion part options are: Previous Hour, Previous 6 Hours, Previous 12 Hours, Previous 24 Hours, Previous 3 Days Previous 7 Days\")",
        user_request,
        "output: "
    ]

    max_retries = 5
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt_parts)
            print(response.text)
            return response
        except google.api_core.exceptions.InternalServerError as e:
            wait_time = 2 ** attempt
            print(
                f"Attempt {attempt+1} failed with error: {e}. Retrying in {wait_time} seconds...")
            time.sleep(wait_time)
    print("Failed to generate instructions after several attempts.")
