from discord import PermissionOverwrite


def get_permissions():
    permissions = PermissionOverwrite(
        add_reactions=False,
        administrator=False,
        attach_files=False,
        ban_members=False,
        change_nickname=False,
        connect=False,
        create_expressions=False,
        create_instant_invite=False,
        create_private_threads=False,
        create_public_threads=False,
        deafen_members=False,
        embed_links=False,
        external_emojis=False,
        external_stickers=False,
        kick_members=False,
        manage_channels=False,
        manage_emojis=False,
        manage_emojis_and_stickers=False,
        manage_events=False,
        manage_expressions=False,
        manage_guild=False,
        manage_messages=False,
        manage_nicknames=False,
        manage_permissions=False,
        manage_roles=False,
        manage_threads=False,
        manage_webhooks=False,
        mention_everyone=False,
        moderate_members=False,
        move_members=False,
        mute_members=False,
        priority_speaker=False,
        read_message_history=False,
        read_messages=False,
        request_to_speak=False,
        send_messages=False,
        send_messages_in_threads=False,
        send_tts_messages=False,
        send_voice_messages=False,
        speak=False,
        stream=False,
        use_application_commands=False,
        use_embedded_activities=False,
        use_external_emojis=False,
        use_external_sounds=False,
        use_external_stickers=False,
        use_soundboard=False,
        use_voice_activation=False,
        view_audit_log=False,
        view_guild_insights=False
    )

    return permissions
