from discord import Permissions


def get_roles_permissions():
    permissions = Permissions(
        add_reactions=True,
        administrator=False,
        attach_files=False,
        ban_members=False,
        change_nickname=False,
        connect=True,
        create_expressions=False,
        create_instant_invite=False,
        create_private_threads=False,
        create_public_threads=True,
        deafen_members=True,
        embed_links=False,
        external_emojis=True,
        external_stickers=True,
        kick_members=False,
        manage_channels=False,
        manage_emojis=False,
        manage_emojis_and_stickers=False,
        manage_events=False,
        manage_expressions=False,
        manage_guild=False,
        manage_messages=True,
        manage_nicknames=False,
        manage_permissions=False,
        manage_roles=False,
        manage_threads=True,
        manage_webhooks=False,
        mention_everyone=False,
        moderate_members=False,
        move_members=True,
        mute_members=True,
        priority_speaker=True,
        read_message_history=True,
        read_messages=True,
        request_to_speak=True,
        send_messages=True,
        send_messages_in_threads=True,
        send_tts_messages=False,
        send_voice_messages=False,
        speak=True,
        stream=True,
        use_application_commands=True,
        use_embedded_activities=False,
        use_external_emojis=True,
        use_external_sounds=True,
        use_external_stickers=True,
        use_soundboard=True,
        use_voice_activation=True,
        view_audit_log=False,
        view_channel=True,
    )

    return permissions